blank_issues_enabled: false
contact_links:
  - name: 🗣️ Ask question
    url: https://github.com/Jonnitto/Jonnitto.OutdatedBrowser/discussions/category_choices
    about: Please ask and answer questions in discussions
