Neos:
  Neos:
    fusion:
      autoInclude:
        'Jonnitto.OutdatedBrowser': true

Jonnitto:
  OutdatedBrowser:
    # Set to `Storage` or `Cookie`
    implementation: Storage
    fallbackLanguage: en
    # Browser based: A23, IE8, IE9, IE10, IE11 or Edge
    # Feature based: Flexbox, oldGrid or Grid
    # Property based: Any CSS property
    lowerThan: Edges
    presets:
      IE8: borderSpacing
      IE9: boxShadow
      IE10: transform
      IE11: borderImage
      Edge: js:Promise
      Flexbox: flex-wrap
      oldGrid: grid-row
      Grid: grid-auto-flow
      A23: writing-mode
